version: '3.3'

services:
    user_account_service:
        build: user_account_service
        ports:
            - "8123:8123"
        links:
            - asset_service
        depends_on:
            - user_data
        environment:
            - "DATABASE_HOST=user_data"
            - "ASSET_SERVICE_HOST=asset_service"
            - "ASSET_SERVICE_PORT=8124"

    user_data:
        build: user_data
        volumes:
            - db_user_data:/var/lib/mysql
        ports:
            - 33061:3306
        environment:
            - "MYSQL_ROOT_PASSWORD=1234"
            - "MYSQL_DATABASE=ABCompany"
            - "MYSQL_USER=user_account_service"
            - "MYSQL_PASSWORD=1234"

    asset_service:
        build: asset_service
        ports:
            - "8124:8124"
        depends_on:
            - asset_mapping
            - asset_mapping_seed
        environment:
            - "DATABASE_URL=mongodb://asset_mapping:27017/user"

    asset_mapping:
        build: asset_mapping
        volumes:
            - db_asset_mapping:/data/db 
        ports:
            - "27018:27017"

    asset_mapping_seed:
        build: asset_mapping_seed
        links:
            - asset_mapping

volumes:
    db_user_data:
    db_asset_mapping: